import type {
  InvoiceFixtureRequest,
  InvoiceLineCanonical,
  InvoiceTotals,
} from "../types/invoice-canonical";
import type { Adjustment } from "../types/commercial-fields";
import { ublValidationError } from "../errors";
import { decimalMultiply, decimalRound, decimalDivide, sumMoney, subtractMoney } from "./decimal";
import { readAssetJson } from "../paths/package-root";

export const commercialFail = (path: string, issue: string): never => {
  throw ublValidationError("Invalid commercial CPE", { details: [{ path, issue }] });
};
export const isCharge = (code: string) => ["46", "47", "48", "49", "50"].includes(code);
export const affectsTax = (code: string) =>
  ["00", "02", "04", "05", "06", "47", "49", "20"].includes(code);
export function validateAdjustment(a: Adjustment, path: string, scope: "line" | "global"): void {
  const allowed = scope === "line" ? ["00", "01", "47", "48"] : ["02", "03", "46", "49", "50"];
  if (!allowed.includes(a.code)) commercialFail(`${path}.code`, `Invalid ${scope} adjustment code`);
  if (a.amount !== decimalRound(a.amount) || a.base_amount !== decimalRound(a.base_amount))
    commercialFail(path, "Amounts must have at most two decimals");
  if (!isCharge(a.code) && a.amount > a.base_amount)
    commercialFail(`${path}.amount`, "Discount exceeds base");
  if (
    a.factor !== undefined &&
    (a.factor !== decimalRound(a.factor, 5) ||
      decimalMultiply(a.base_amount, a.factor) !== a.amount)
  )
    commercialFail(`${path}.factor`, "Factor (up to five decimals) and base must produce amount");
}
export function applyAdjustments(base: number, adjustments: Adjustment[], taxOnly = false): number {
  const included = adjustments.filter((a) => !taxOnly || affectsTax(a.code));
  return subtractMoney(
    sumMoney([base, ...included.filter((a) => isCharge(a.code)).map((a) => a.amount)]),
    sumMoney(included.filter((a) => !isCharge(a.code)).map((a) => a.amount)),
  );
}
function catalogHas(catalog: string, code: string): boolean {
  return (
    readAssetJson<{ catalogs: Record<string, { code: string }[]> }>(
      "assets/catalogs/commercial-catalogs.json",
    ).catalogs[catalog]?.some((item) => item.code === code) ?? false
  );
}

/** Document-wide adjustments change header taxes, without rewriting signed line bases. */
export function finishCommercial(
  request: InvoiceFixtureRequest,
  lines: InvoiceLineCanonical[],
  totals: InvoiceTotals,
  quotaAdjustment = false,
): void {
  const fail = commercialFail;
  const global = request.adjustments ?? [];
  global.forEach((a, i) => {
    validateAdjustment(a, `adjustments.${i}`, "global");
    if (a.tier_range || a.related_percent !== undefined)
      fail(`adjustments.${i}`, "ISC advance metadata is generated by the server");
    if (
      a.tax_affectation &&
      !lines.some(
        (l) =>
          l.tax_affectation === a.tax_affectation &&
          l.tax_scheme_id === (a.tax_scheme_id ?? "1000") &&
          (a.percent === undefined || l.igv_percent === a.percent),
      )
    )
      fail(`adjustments.${i}.tax_affectation`, "Fiscal category must match the selected tax group");
  });
  const advances = request.prepayments ?? [];
  if (
    new Set(advances.map((a) => a.id)).size !== advances.length ||
    new Set(
      advances.map(
        (a) => `${a.issuer_ruc}/${a.document_type}/${a.serie_number.replace(/-0*(\d+)$/, "-$1")}`,
      ),
    ).size !== advances.length
  )
    fail("prepayments", "Duplicate prepayment ID or document");
  const computed: Adjustment[] = global.map((a) => ({ ...a }));
  let advanceTax = 0;
  for (const [i, advance] of advances.entries()) {
    const path = `prepayments.${i}`;
    if (
      [advance.amount, advance.base_amount, advance.isc_amount ?? 0].some(
        (value) => value !== decimalRound(value),
      )
    )
      fail(path, "Prepayment monetary amounts require at most two decimals");
    if (advance.paid_date > request.issue_date)
      fail(`${path}.paid_date`, "Prepayment date cannot be after issue date");
    if (advance.serie_number.startsWith("F") !== (advance.document_type === "01"))
      fail(`${path}.serie_number`, "Prepayment series/type mismatch");
    const percent =
      advance.percent ??
      (advance.tax_affectation === "10" ? 18 : advance.tax_affectation === "17" ? 4 : 0);
    if (["20", "30"].includes(advance.tax_affectation) && percent !== 0)
      fail(`${path}.percent`, "Exempt/unaffected advance has zero tax");
    const isc = advance.isc_amount ?? 0;
    if (isc && (!advance.isc_system || advance.isc_percent === undefined))
      fail(`${path}.isc_system`, "ISC advances require system and effective ISC rate");
    const vat = decimalMultiply(sumMoney([advance.base_amount, isc]), percent, 100);
    if (sumMoney([advance.base_amount, isc, vat]) !== advance.amount)
      fail(`${path}.amount`, "Advance must equal base plus its taxes");
    advanceTax = sumMoney([advanceTax, vat, isc]);
    computed.push({
      code:
        advance.tax_affectation === "20" ? "05" : advance.tax_affectation === "30" ? "06" : "04",
      base_amount: advance.base_amount,
      amount: advance.base_amount,
      tax_affectation: advance.tax_affectation,
      tax_scheme_id:
        advance.tax_affectation === "17"
          ? "1016"
          : advance.tax_affectation === "10"
            ? "1000"
            : advance.tax_affectation === "20"
              ? "9997"
              : "9998",
      percent,
    });
    if (isc)
      computed.push({
        code: "20",
        base_amount: advance.base_amount,
        amount: isc,
        tax_scheme_id: "2000",
        percent: advance.isc_percent,
        tier_range: advance.isc_system,
        related_percent: percent,
      });
  }
  for (const [i, a] of computed.entries()) {
    if (!affectsTax(a.code)) continue;
    const groups = totals.tax_subtotals.filter(
      (g) =>
        g.tax_scheme_id === (a.tax_scheme_id ?? "1000") &&
        (a.percent === undefined || g.percent === a.percent) &&
        (a.tier_range === undefined || g.tier_range === a.tier_range),
    );
    if (groups.length !== 1)
      fail(`adjustments.${i}.tax_scheme_id`, "Select exactly one existing tax scheme and rate");
    const group = groups[0] ?? fail(`adjustments.${i}`, "Missing tax group");
    a.tax_scheme_id = group.tax_scheme_id;
    a.percent = group.percent;
    if (group.tax_scheme_id === "9996" || group.tax_scheme_id === "7152")
      fail(`adjustments.${i}`, "Free operations and bag units cannot receive base adjustments");
    if (["02", "49"].includes(a.code) && !["1000", "1016"].includes(group.tax_scheme_id))
      fail(`adjustments.${i}.code`, "Code 02/49 applies to IGV/IVAP bases");
    if (a.code !== "20") group.taxable_amount = applyAdjustments(group.taxable_amount, [a]);
    if (group.tax_scheme_id === "2000" && a.code === "20") {
      group.tax_amount = subtractMoney(group.tax_amount, a.amount);
      const vat = totals.tax_subtotals.find(
        (g) => g.tax_scheme_id === "1000" && g.percent === a.related_percent,
      );
      if (vat) {
        vat.tax_amount = subtractMoney(vat.tax_amount, decimalMultiply(a.amount, vat.percent, 100));
      }
    } else if (["1000", "1016"].includes(group.tax_scheme_id)) {
      // Keep line rounding, adjusting only the taxable amount of the global operation.
      const delta = decimalMultiply(a.amount, group.percent, 100);
      group.tax_amount = isCharge(a.code)
        ? sumMoney([group.tax_amount, delta])
        : subtractMoney(group.tax_amount, delta);
    }
  }
  const taxFor = (scheme: string) =>
    sumMoney(
      totals.tax_subtotals.filter((g) => g.tax_scheme_id === scheme).map((g) => g.tax_amount),
    );
  const baseFor = (scheme: string) =>
    sumMoney(
      totals.tax_subtotals.filter((g) => g.tax_scheme_id === scheme).map((g) => g.taxable_amount),
    );
  totals.tax_amount = sumMoney(totals.tax_subtotals.map((g) => g.tax_amount));
  totals.taxed_amount = sumMoney([baseFor("1000"), baseFor("1016")]);
  totals.free_amount = sumMoney(
    lines.filter((l) => l.is_free).map((l) => decimalMultiply(l.unit_value, l.quantity)),
  );
  totals.exempt_amount = baseFor("9997");
  totals.unaffected_amount = baseFor("9998");
  totals.igv_amount = taxFor("1000");
  totals.ivap_amount = taxFor("1016");
  totals.isc_amount = taxFor("2000");
  totals.icbper_amount = taxFor("7152");
  totals.prepaid_amount = sumMoney(advances.map((a) => a.amount));
  totals.advance_tax_amount = advanceTax;
  // Item discounts already change LineExtensionAmount; non-tax item adjustments change the payable total.
  const nonTaxItem = lines.flatMap((l) => (l.adjustments ?? []).filter((a) => !affectsTax(a.code)));
  totals.line_extension_amount = applyAdjustments(totals.line_extension_amount, global, true);
  totals.tax_inclusive_amount = sumMoney([
    totals.line_extension_amount,
    subtractMoney(
      sumMoney([totals.tax_amount, ...lines.filter((l) => l.is_free).map((l) => l.isc_amount)]),
      totals.free_tax_amount,
    ),
    advanceTax,
  ]);
  const nonTax = [...global.filter((a) => !affectsTax(a.code)), ...nonTaxItem];
  totals.allowance_total_amount = sumMoney(
    nonTax.filter((a) => !isCharge(a.code)).map((a) => a.amount),
  );
  totals.charge_total_amount = sumMoney(
    nonTax.filter((a) => isCharge(a.code)).map((a) => a.amount),
  );
  totals.payable_amount = subtractMoney(
    applyAdjustments(totals.tax_inclusive_amount, nonTax),
    totals.prepaid_amount,
  );
  totals.computed_adjustments = computed;

  const exchange = request.exchange_rate;
  if (
    exchange &&
    (exchange.source_currency !== request.currency ||
      exchange.source_currency === "PEN" ||
      exchange.date > request.issue_date)
  )
    fail(
      "exchange_rate",
      "Exchange rate must match the foreign document currency and a date on/before issue date",
    );
  const d = request.detraction;
  const detractionOperation = /^100[1-4]$/.test(request.operation_type);
  if (detractionOperation !== Boolean(d))
    fail(
      "detraction",
      "Operation 1001-1004 requires detraction, and other operations cannot include it",
    );
  if (d) {
    if (!catalogHas("54", d.goods_code)) fail("detraction.goods_code", "Unknown catalog 54 code");
    if (!catalogHas("59", d.payment_means_code))
      fail("detraction.payment_means_code", "Unknown catalog 59 code");
    const specialized = { "1002": "004", "1003": "028", "1004": "027" }[request.operation_type];
    if (specialized && specialized !== d.goods_code)
      fail("detraction.goods_code", "Goods code does not match specialized operation");
    if (request.currency !== "PEN" && !exchange)
      fail("exchange_rate", "Foreign-currency detraction requires an explicit PEN rate");
    const salePen =
      request.currency === "PEN"
        ? sumMoney([totals.payable_amount, totals.prepaid_amount])
        : decimalMultiply(
            sumMoney([totals.payable_amount, totals.prepaid_amount]),
            exchange?.rate ?? 1,
          );
    const reference = sumMoney(lines.map((l) => l.cargo_transport?.reference_amount ?? 0));
    const base = request.operation_type === "1004" ? Math.max(salePen, reference) : salePen;
    if (request.operation_type === "1004" && d.percent !== 4)
      fail("detraction.percent", "Cargo transport detraction rate must be 4");
    if (decimalMultiply(base, d.percent, 100, 0) !== d.amount)
      fail("detraction.amount", "Detraction must match the rounded PEN amount (whole soles)");
  }
  for (const [i, l] of lines.entries()) {
    for (const [op, field] of [
      ["1002", "hydrobiology"],
      ["1003", "passenger_transport"],
      ["1004", "cargo_transport"],
    ] as const) {
      if ((request.operation_type === op) !== Boolean(l[field]))
        fail(`lines.${i}.${field}`, `Field is required only for operation ${op}`);
    }
    if (l.icbper) {
      if (l.icbper.quantity !== Math.round(l.quantity))
        fail(
          `lines.${i}.icbper.quantity`,
          "Bag units must equal the rounded line quantity; use a separate bag line for a different count",
        );
      const year = Number(request.issue_date.slice(0, 4));
      const rate = year >= 2023 ? 0.5 : year >= 2019 ? (year - 2018) / 10 : 0;
      if (!rate || request.issue_date < "2019-08-01")
        fail(`lines.${i}.icbper`, "ICBPER is not effective on issue date");
      const expected =
        request.currency === "PEN"
          ? rate
          : exchange
            ? decimalDivide(rate, exchange.rate, 5)
            : fail("exchange_rate", "ICBPER in foreign currency requires an explicit rate");
      if (l.icbper.per_unit_amount !== expected)
        fail(
          `lines.${i}.icbper.per_unit_amount`,
          `Expected ${expected} for issue date and currency`,
        );
    }
  }
  request.payment_means?.forEach((m, i) => {
    if (!catalogHas("59", m.code)) fail(`payment_means.${i}.code`, "Unknown catalog 59 code");
  });
  const terms = request.payment_terms;
  if (terms?.condition === "credit") {
    if (terms.currency !== request.currency)
      fail("payment_terms.currency", "Credit currency must match document currency");
    const installmentIds = terms.installments.map((q) => q.number);
    if (new Set(installmentIds).size !== installmentIds.length)
      fail("payment_terms.installments", "Duplicate installment number");
    let lastDate = request.issue_date;
    terms.installments.forEach((q, i) => {
      if (
        q.number !== i + 1 ||
        q.due_date <= request.issue_date ||
        q.due_date < lastDate ||
        q.amount !== decimalRound(q.amount)
      )
        fail(
          `payment_terms.installments.${i}`,
          "Installments must be numbered sequentially, ordered by future dates and use two decimal amounts",
        );
      lastDate = q.due_date;
    });
    if (request.due_date && request.due_date !== lastDate)
      fail("due_date", "Due date must equal the last installment date");
    if (sumMoney(terms.installments.map((q) => q.amount)) !== terms.outstanding_amount)
      fail("payment_terms.outstanding_amount", "Installments must sum to outstanding amount");
    const detractionInCurrency = d
      ? request.currency === "PEN"
        ? d.amount
        : decimalDivide(d.amount, exchange?.rate ?? 1, 2)
      : 0;
    const net = subtractMoney(totals.payable_amount, detractionInCurrency);
    if (terms.outstanding_amount !== net && !quotaAdjustment)
      fail("payment_terms.outstanding_amount", `Expected net pending amount ${net}`);
  }
}
